let consoles = [
  // !!ORDER MATTERS!!
  {original: "Atari 2600", translation: "Atari 2600"},
  {original: "Atari 5200", translation: "Atari 5200"},
  {original: "Atari 7800", translation: "Atari 7800"},
  {original: "Atari Jaguar", translation: "Atari Jaguar"},
  {original: "Atari Lynx", translation: "Atari Lynx"},
  {original: "Colecovision", translation: "Coleco Colecovision"},
  {original: "Odyssey 2", translation: "Magnavox Odyssey 2"},
  {original: "Intellivision", translation: "Matel Intellivision"},
  {original: "Xbox 360", translation: "Microsoft Xbox 360"},
  {original: "Xbox One", translation: "Microsoft Xbox One"},
  {original: "Xbox", translation: "Microsoft Xbox"},
  {original: "Turbo Duo", translation: "NEC Turbo Duo"},
  {original: "Turbo Grafx 16", translation: "NEC Turbo Grafx 16"},
  {original: "Neo Geo AES", translation: "Neo Geo AES"},
  {original: "Neo Geo MVS", translation: "Neo Geo MVS"},
  {original: "Neo Geo Pocket", translation: "Neo Geo Pocket"},
  {original: "3DS", translation: "Nintendo 3DS"},
  {original: "DS", translation: "Nintendo DS"},
  {original: "Gameboy Color", translation: "Nintendo Gameboy Color"},
  {original: "Gamecube", translation: "Nintendo Gamecube"},
  {original: "GBA", translation: "Nintendo GBA Gameboy Advance"},
  {original: "Gameboy", translation: "Nintendo Gameboy"},
  {original: "N64", translation: "Nintendo N64"},
  {original: "NES", translation: "Nintendo NES"},
  {original: "SNES", translation: "Nintendo SNES Super"},
  {original: "Nintendo Switch", translation: "Nintendo Switch"},
  {original: "Virtual Boy", translation: "Nintendo Virtual Boy"},
  {original: "WIIU", translation: "Nintendo Wii U"},
  {original: "WII-U", translation: "Nintendo Wii U"},
  {original: "WII", translation: "Nintendo Wii"},
  {original: "N Gage", translation: "Nokia N Gage"},
  {original: "3DO", translation: "Panasonic 3DO"},
  {original: "CD-i", translation: "Phillips CD-i"},
  {original: "32X", translation: "Sega 32X"},
  {original: "Sega CD", translation: "Sega CD"},
  {original: "Dreamcast", translation: "Sega Dreamcast"},
  {original: "Game Gear", translation: "Sega Game Gear"},
  {original: "Genesis", translation: "Sega Genesis"},
  {original: "Master System", translation: "Sega Master System"},
  {original: "Saturn", translation: "Sega Saturn"},
  {original: "PS4", translation: "Sony PS4 Playstation 4"},
  {original: "PS3", translation: "Sony PS3 Playstation 3"},
  {original: "PS2", translation: "Sony PS2 Playstation 2"},
  {original: "PS1", translation: "Sony PS1 Playstation 1"},
  {original: "PSP", translation: "Sony PSP"},
  {original: "PS Vita", translation: "Sony PSP Vita"},
  {original: "Vectrex", translation: "Vectrex"},
  //!!Clean Up
  {original: "Vita", translation: "Sony PSP Vita"},
  {original: "360", translation: "Microsoft Xbox 360"},
  {original: "Nintendo DS", translation: "Nintendo DS"},
  {original: "New 3DS", translation: "Nintendo 3DS"},
  {original: "Commodore 64", translation: "Commodore 64"}
];

let prices = {
  "Atari 2600": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Atari 5200": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Atari 7800": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Atari Jaguar": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Atari Lynx": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Coleco Colecovision": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Commodore 64": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Magnavox Odyssey 2": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Matel Intellivision": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true, overlay: true},
  "Microsoft Xbox 360": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: true, cartOnly: false, cartPlus: false, gameBox: false},
  "Microsoft Xbox One": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: true, cartOnly: false, cartPlus: false, gameBox: false},
  "Microsoft Xbox": {buyIn: true, discOnly: false, discPlus: true, instructionManual: true, coverArt: true, cartOnly: false, cartPlus: false, gameBox: false},
  "NEC Turbo Duo": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: false, cartOnly: false, cartPlus: false, gameBox: false, rearArt: true},
  "NEC Turbo Grafx 16": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Neo Geo AES": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Neo Geo MVS": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Neo Geo Pocket": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: false},
  "Nintendo 3DS": {btrueuyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: false},
  "Nintendo DS": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: false},
  "Nintendo Gameboy Color": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Nintendo Gamecube": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: true, cartOnly: false, cartPlus: false, gameBox: false},
  "Nintendo GBA Gameboy Advance": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: true},
  "Nintendo Gameboy": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Nintendo N64": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Nintendo NES": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Nintendo SNES Super": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Nintendo Switch": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: false},
  "Nintendo Virtual Boy": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Nintendo Wii U": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: true, cartOnly: false, cartPlus: false, gameBox: false},
  "Nintendo Wii": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: true, cartOnly: false, cartPlus: false, gameBox: false},
  "Nokia N Gage": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: false},
  "Panasonic 3DO": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: false, cartOnly: false, cartPlus: false, gameBox: true},
  "Phillips CD-i": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: false, cartOnly: false, cartPlus: false, gameBox: true},
  "Sega 32X": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Sega CD": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: false, cartOnly: false, cartPlus: false, gameBox: false, rearArt: true},
  "Sega Dreamcast": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: false, cartOnly: false, cartPlus: false, gameBox: false, rearArt: true},
  "Sega Game Gear": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true},
  "Sega Genesis": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: false},
  "Sega Master System": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: false, rearArt: true},
  "Sega Saturn": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: false, cartOnly: false, cartPlus: false, gameBox: false, rearArt: true},
  "Sony PS4 Playstation 4": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: true, cartOnly: false, cartPlus: false, gameBox: false},
  "Sony PS3 Playstation 3": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: true, cartOnly: false, cartPlus: false, gameBox: false},
  "Sony PS2 Playstation 2": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: true, cartOnly: false, cartPlus: false, gameBox: false},
  "Sony PS1 Playstation 1": {buyIn: true, discOnly: true, discPlus: true, instructionManual: true, coverArt: false, cartOnly: false, cartPlus: false, gameBox: false, rearArt: true},
  "Sony PSP": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: false},
  "Sony PSP Vita": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: true, cartOnly: true, cartPlus: true, gameBox: false},
  "Vectrex": {buyIn: true, discOnly: false, discPlus: false, instructionManual: true, coverArt: false, cartOnly: true, cartPlus: true, gameBox: true}
}

module.exports = {consoles, prices}
