module.exports = [
  { input: 'HARDWARE', output: ['Hardware'] },
  { input: 'ELECTRONICS', output: ['Electronic'] },
  { input: 'SYSTEM PACK', output: ['System Pack'] },
  { input: 'CONTROLLERS', output: ['Controller'] },
  { input: 'CONTROLLER', output: ['Controller'] },
  { input: 'ACCESSORY', output: ['Accessory'] },
  { input: 'MP3 PLAYERS', output: ['MP3 Player'] },
  { input: 'UNIVERSAL', output: ['Universal'] },
  { input: 'CORD', output: ['Cord'] },
  { input: 'CORDS', output: ['Cord'] },
  { input: 'CABLE', output: ['Cord'] },
  { input: 'CABLES', output: ['Cord'] },
  { input: 'TABLETS', output: ['Tablet'] },
  { input: 'PHONE', output: ['Phone'] },
  { input: 'Computer', output: ['Computer'] },
  // Consoles
  { input: '3DS', output: ['Nintendo', '3DS'] },
  { input: 'WII/WII-U', output: ['Nintendo', 'Wii', 'Wii U'] },
  { input: 'WII', output: ['Nintendo', 'Wii'] },
  { input: 'WII-U', output: ['Nintendo', 'Wii U'] },
  { input: 'WIIU', output: ['Nintendo', 'Wii U'] },
  { input: 'XBOX 360', output: ['Microsoft', 'Xbox 360'] },
  { input: 'XBOX ONE', output: ['Microsoft', 'Xbox One'] },
  { input: 'XBOX One', output: ['Microsoft', 'Xbox One'] },
  { input: 'XBOX', output: ['Microsoft', 'Xbox'] },
  { input: 'SNES', output: ['Nintendo', 'SNES', 'Super Nintendo'] },
  { input: 'NES', output: ['Nintendo', 'NES'] },
  { input: 'N64', output: ['Nintendo', 'N64', 'Nintendo 64'] },
  { input: 'N64', output: ['Sega', 'Dreamcast'] },
  { input: 'GAME GEAR', output: ['Sega', 'Game Gear'] },
  { input: 'GAMEBOY COLOR', output: ['Nintendo', 'Gameboy Color'] },
  { input: 'GAMEBOY', output: ['Nintendo', 'Gameboy'] },
  { input: 'GBA', output: ['Nintendo', 'GBA', 'Gameboy Advance'] },
  { input: 'GAMECUBE', output: ['Nintendo', 'Gamecube'] },
  { input: 'GENESIS', output: ['Sega', 'Genesis'] },
  { input: 'MASTER SYSTEM', output: ['Sega', 'Master System'] },
  { input: 'PS VITA', output: ['Sony', 'PS Vita', 'Vita' ] },
  { input: 'PSP', output: ['Sony', 'PSP' ] },
  { input: 'PS1/PS2/PS3', output: ['Sony', 'PS1', 'PS2', 'PS3', 'Playstation 1', 'Playstation 2', 'Playstation 3' ] },
  { input: 'PS2/PS3', output: ['Sony', 'PS2', 'PS3', 'Playstation 2', 'Playstation 3' ] },
  { input: 'PS1', output: ['Sony', 'PS1', 'Playstation 1' ] },
  { input: 'PS2', output: ['Sony', 'PS2', 'Playstation 2' ] },
  { input: 'PS3', output: ['Sony', 'PS3', 'Playstation 3' ] },
  { input: 'PS4', output: ['Sony', 'PS4', 'Playstation 4' ] },
  { input: 'SATURN', output: ['Sega', 'Saturn' ] },
  { input: 'SATURN', output: ['Sega', 'Sega CD' ] },
  { input: 'SWITCH', output: ['Nintendo', 'Switch' ] }
]
