module.exports = [
  { input: 'HARDWARE', output: ['Hardware'], subname: 'Hardware' },
  { input: 'ELECTRONICS', output: ['Electronic'], subname: 'Electronic' },
  // { input: 'SYSTEM PACK', output: ['System Pack'], subname: 'System Pack' },
  { input: 'CONTROLLERS', output: ['Controller'], subname: 'Controller' },
  { input: 'CONTROLLER', output: ['Controller'], subname: 'Controller' },
  { input: 'ACCESSORY', output: ['Accessory'], subname: 'Accessory' },
  { input: 'MP3 PLAYERS', output: ['MP3 Player'], subname: 'MP3 Player' },
  { input: 'UNIVERSAL', output: ['Universal'], subname: 'Universal' },
  { input: 'CORDS', output: ['Cord'], subname: 'Cord' },
  { input: 'CORD', output: ['Cord'], subname: 'Cord' },
  { input: 'CABLES', output: ['Cord'], subname: 'Cord' },
  { input: 'CABLE', output: ['Cord'], subname: 'Cord' },
  { input: 'TABLETS', output: ['Tablet'], subname: 'Tablet' },
  { input: 'PHONE', output: ['Phone'], subname: 'Phone' },
  { input: 'SERVICE', output: ['Service'], subname: 'Service' },
  { input: 'Computer', output: ['Computer'], subname: 'Computer' },
  // Consoles
  { input: 'New 2DS', output: ['Nintendo', '2DS', 'XL', 'New 2DS'], subname: 'Nintendo New 2DS XL' },
  { input: '2DS', output: ['Nintendo', '2DS'], subname: 'Nintendo 2DS' },
  { input: 'New 3DS XL', output: ['Nintendo', '3DS', 'XL', 'New 3DS'], subname: 'Nintendo New 3DS XL' },
  { input: '3DS XL', output: ['Nintendo', '3DS', 'XL'], subname: 'Nintendo 3DS XL' },
  { input: '3DS', output: ['Nintendo', '3DS'], subname: 'Nintendo 3DS' },
  { input: 'WII/WII-U', output: ['Nintendo', 'Wii', 'Wii U'], subname: 'Nintendo Wii/Wii U' },
  { input: 'WII', output: ['Nintendo', 'Wii'], subname: 'Nintendo Wii' },
  { input: 'Wii', output: ['Nintendo', 'Wii'], subname: 'Nintendo Wii' },
  { input: 'WII-U', output: ['Nintendo', 'Wii U'], subname: 'Nintendo Wii U' },
  { input: 'WIIU', output: ['Nintendo', 'Wii U'], subname: 'Nintendo Wii U' },
  { input: 'WiiU', output: ['Nintendo', 'Wii U'], subname: 'Nintendo Wii U' },
  { input: 'XBOX 360', output: ['Microsoft', 'Xbox 360'], subname: 'Microsoft Xbox 360' },
  { input: 'XBOX ONE', output: ['Microsoft', 'Xbox One'], subname: 'Microsoft Xbox One' },
  { input: 'Xbox One', output: ['Microsoft', 'Xbox One'], subname: 'Microsoft Xbox One' },
  { input: 'XBOX One', output: ['Microsoft', 'Xbox One'], subname: 'Microsoft Xbox One' },
  { input: 'XBOX', output: ['Microsoft', 'Xbox'], subname: 'Microsoft Xbox' },
  { input: 'SNES', output: ['Nintendo', 'SNES', 'Super Nintendo'], subname: 'Nintendo SNES Super' },
  { input: 'Super Nintendo Entertainment System', output: ['Nintendo', 'SNES', 'Super Nintendo'], subname: 'Nintendo SNES Super' },
  { input: 'NES', output: ['Nintendo', 'NES'], subname: 'Nintendo NES' },
  { input: 'Original Nintendo Entertainment System', output: ['Nintendo', 'NES'], subname: 'Nintendo NES' },
  { input: 'N64', output: ['Nintendo', 'N64', 'Nintendo 64'], subname: 'Nintendo N64' },
  { input: 'Nintendo 64', output: ['Nintendo', 'N64', 'Nintendo 64'], subname: 'Nintendo N64' },
  { input: 'Sega Dreamcast', output: ['Sega', 'Dreamcast'], subname: 'Sega Dreamcast' },
  { input: 'DREAMCAST', output: ['Sega', 'Dreamcast'], subname: 'Sega Dreamcast' },
  { input: 'GAME GEAR', output: ['Sega', 'Game Gear'], subname: 'Sega Game Gear' },
  { input: 'GAMEBOY COLOR', output: ['Nintendo', 'Gameboy Color'], subname: 'Nintendo Gameboy Color' },
  { input: 'GAMEBOY', output: ['Nintendo', 'Gameboy'], subname: 'Nintendo Gameboy' },
  { input: 'GBA', output: ['Nintendo', 'GBA', 'Gameboy Advance'], subname: 'Nintendo GBA Gameboy Advance' },
  { input: 'GAMECUBE', output: ['Nintendo', 'Gamecube'], subname: 'Nintendo Gamecube' },
  { input: 'GENESIS', output: ['Sega', 'Genesis'], subname: 'Sega Genesis' },
  { input: 'MASTER SYSTEM', output: ['Sega', 'Master System'], subname: 'Sega Master System' },
  { input: 'Sega Master System', output: ['Sega', 'Master System'], subname: 'Sega Master System' },
  { input: 'PS VITA', output: ['Sony', 'PS Vita', 'Vita' ], subname: 'Sony PSP Vita' },
  { input: 'PS Vita', output: ['Sony', 'PS Vita', 'Vita' ], subname: 'Sony PSP Vita' },
  { input: 'PSP', output: ['Sony', 'PSP' ], subname: 'Sony PSP' },
  { input: 'PS1/PS2/PS3', output: ['Sony', 'PS1', 'PS2', 'PS3', 'Playstation 1', 'Playstation 2', 'Playstation 3'], subname: 'Sony PS1/PS2/PS3' },
  { input: 'PS2/PS3', output: ['Sony', 'PS2', 'PS3', 'Playstation 2', 'Playstation 3' ], subname: 'Sony PS2/PS3' },
  { input: 'PS1', output: ['Sony', 'PS1', 'Playstation 1' ], subname: 'Sony PS1 Playstation 1' },
  { input: 'Playstation Original', output: ['Sony', 'PS1', 'Playstation 1' ], subname: 'Sony PS1 Playstation 1' },
  { input: 'PS2', output: ['Sony', 'PS2', 'Playstation 2' ], subname: 'Sony PS2 Playstation 2' },
  { input: 'Playstation 2', output: ['Sony', 'PS2', 'Playstation 2' ], subname: 'Sony PS2 Playstation 2' },
  { input: 'PS3', output: ['Sony', 'PS3', 'Playstation 3' ], subname: 'Sony PS3 Playstation 3' },
  { input: 'Playstation 3', output: ['Sony', 'PS3', 'Playstation 3' ], subname: 'Sony PS3 Playstation 3' },
  { input: 'PS4', output: ['Sony', 'PS4', 'Playstation 4' ], subname: 'Sony PS4 Playstation 4' },
  { input: 'Playstation 4', output: ['Sony', 'PS4', 'Playstation 4' ], subname: 'Sony PS4 Playstation 4' },
  { input: 'SATURN', output: ['Sega', 'Saturn' ], subname: 'Sega Saturn' },
  { input: 'SEGA CD', output: ['Sega', 'Sega CD' ], subname: 'Sega CD' },
  { input: 'Nintendo Switch', output: ['Nintendo', 'Switch' ], subname: 'Nintendo Switch' },
  { input: 'SWITCH', output: ['Nintendo', 'Switch' ], subname: 'Nintendo Switch' },
  { input: 'Atari 2600', output: ['Atari', '2600' ], subname: 'Atari 2600' },
  { input: 'Atari 5200', output: ['Atari', '5200' ], subname: 'Atari 5200' },
  { input: 'Atari 7800', output: ['Atari', '7800' ], subname: 'Atari 7800' },
  { input: 'Atari Jaguar', output: ['Atari', 'Jaguar' ], subname: 'Atari Jaguar' },
  { input: 'TurboDuo (TurboGrafx Dual-System)', output: ['TurboGrafx', 'TurboDuo' ], subname: 'TurboGrafx TurboDuo' },
]
