module.exports = [
  // !!ORDER MATTERS!!
  {original: 'Atari 2600', translation: 'Atari 2600'},
  {original: 'Atari 5200', translation: 'Atari 5200'},
  {original: 'Atari 7800', translation: 'Atari 7800'},
  {original: 'Atari Jaguar', translation: 'Atari Jaguar'},
  {original: 'Atari Lynx', translation: 'Atari Lynx'},
  {original: 'Colecovision', translation: 'Coleco Colecovision'},
  {original: 'Odyssey 2', translation: 'Magnavox Odyssey 2'},
  {original: 'Intellivision', translation: 'Matel Intellivision'},
  {original: 'Xbox 360', translation: 'Microsoft Xbox 360'},
  {original: 'Xbox One', translation: 'Microsoft Xbox One'},
  {original: 'Xbox', translation: 'Microsoft Xbox'},
  {original: 'Turbo Duo', translation: 'NEC Turbo Duo'},
  {original: 'Turbo Grafx 16', translation: 'NEC Turbo Grafx 16'},
  {original: 'Neo Geo AES', translation: 'Neo Geo AES'},
  {original: 'Neo Geo MVS', translation: 'Neo Geo MVS'},
  {original: 'Neo Geo Pocket', translation: 'Neo Geo Pocket'},
  {original: '3DS', translation: 'Nintendo 3DS'},
  {original: 'DS', translation: 'Nintendo DS'},
  {original: 'Gameboy Color', translation: 'Nintendo Gameboy Color'},
  {original: 'Gamecube', translation: 'Nintendo Gamecube'},
  {original: 'GBA', translation: 'Nintendo GBA Gameboy Advance'},
  {original: 'Gameboy', translation: 'Nintendo Gameboy'},
  {original: 'N64', translation: 'Nintendo N64'},
  {original: 'NES', translation: 'Nintendo NES'},
  {original: 'SNES', translation: 'Nintendo SNES Super'},
  {original: 'Nintendo Switch', translation: 'Nintendo Switch'},
  {original: 'Virtual Boy', translation: 'Nintendo Virtual Boy'},
  {original: 'WIIU', translation: 'Nintendo Wii U'},
  {original: 'WII-U', translation: 'Nintendo Wii U'},
  {original: 'WII', translation: 'Nintendo Wii'},
  {original: 'N Gage', translation: 'Nokia N Gage'},
  {original: '3DO', translation: 'Panasonic 3DO'},
  {original: 'CD-i', translation: 'Phillips CD-i'},
  {original: '32X', translation: 'Sega 32X'},
  {original: 'Sega CD', translation: 'Sega CD'},
  {original: 'Dreamcast', translation: 'Sega Dreamcast'},
  {original: 'Game Gear', translation: 'Sega Game Gear'},
  {original: 'Genesis', translation: 'Sega Genesis'},
  {original: 'Master System', translation: 'Sega Master System'},
  {original: 'Saturn', translation: 'Sega Saturn'},
  {original: 'PS4', translation: 'Sony PS4 Playstation 4'},
  {original: 'PS3', translation: 'Sony PS3 Playstation 3'},
  {original: 'PS2', translation: 'Sony PS2 Playstation 2'},
  {original: 'PS1', translation: 'Sony PS1 Playstation 1'},
  {original: 'PSP', translation: 'Sony PSP'},
  {original: 'PS Vita', translation: 'Sony PSP Vita'},
  {original: 'Vectrex', translation: 'Vectrex'},
  //!!Clean Up
  {original: 'Vita', translation: 'Sony PSP Vita'},
  {original: '360', translation: 'Microsoft Xbox 360'},
  {original: 'Nintendo DS', translation: 'Nintendo DS'},
  {original: 'New 3DS', translation: 'Nintendo 3DS'},
  {original: 'Commodore 64', translation: 'Commodore 64'}
];
